--- 
javascripts: 
- base: 
  - jquery
  - parseuri
  - jquery-ui
  - jquery.autovideo
  - jquery.json
  - jquery.treeTable
  - jquery.localscroll
  - jquery.textarea
  - showdown
  - jquery.notifyBar
  - jquery.mousewheel
  - jquery.autogrow
  - jquery.scrollTo
  - jquery.form
  - jquery.dynatree.min
  - jquery.cookie
  - jquery.dimensions.min
  - jquery.sprintf
  - jquery.treeview.async
  - jquery.wysiwyg
  - jquery.geekga-1.1.min
  - jquery.treeview
  - jquery.autocomplete
  - components/search
  - highlight/prettify
  - application
  - modules/googlean      
  - modules/index_welcome  
  - modules/move_group   
  - modules/sessions     
  - modules/themes
  - modules/index_question
  - modules/members      
  - modules/new_question
  - modules/show_question
  - openid/js/jquery.openid
  - openid/js/jquery.openid.min

stylesheets: 
- base: 
  - jquery-ui
  - compiled/application
  - prettify
  - /javascripts/openid/css/style.css

