---
javascripts:
- base:
  - jquery
  - rails
  - jquery.json-2.2.min
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - jHtmlArea
  - jquery.notifyBar
  - showdown
  - highlight/prettify
  - components/search
  - jqueryui.ricodigoComplete
  - application
  - modules/index_question
  - modules/retag
  - modules/new_question
  - modules/index_welcome
  - modules/show_user
  - modules/index_group
  - modules/index_user
  - modules/tags_question
  - modules/members
  - modules/move_group
  - modules/editor
  - modules/notifier
  - multiauth

- mobile:
  - jquery
  - rails


- websocket:
  - web-socket-js/swfobject
  - web-socket-js/FABridge
  - web-socket-js/web_socket
  - websocket

- show:
  - jquery.autovideo
  - modules/single/question
  - modules/show_question

stylesheets:
- base:
  - ui-lightness/jquery-ui
  - compiled/application
  - multiauth
  - prettify


