package_assets:         on          # (on, off, always)
embed_assets:           datauri          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           packages    # (defaults to assets)
javascript_compressor:  closure     # (yui, closure)

javascripts:
  base:
    - public/javascripts/app/modules/*.js
    - public/javascripts/vendor/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/vendor/jquery.json-2.2.min.js
    - public/javascripts/vendor/jquery.tools.min.js
    - public/javascripts/vendor/jquery-ui.js
    - public/javascripts/vendor/jquery.textarea.js
    - public/javascripts/vendor/jHtmlArea.js
    - public/javascripts/vendor/jquery.notifyBar.js
    - public/javascripts/vendor/showdown.js
    - public/javascripts/vendor/highlight/prettify.js
    - public/javascripts/app/initializers/search.js
    - public/javascripts/vendor/jqueryui.ricodigoComplete.js
    - public/javascripts/vendor/jquery.cookie.js
    - public/javascripts/application.js

    - public/javascripts/app/initializers/index_question.js
    - public/javascripts/app/initializers/retag.js
    - public/javascripts/app/initializers/new_question.js
    - public/javascripts/app/initializers/index_welcome.js
    - public/javascripts/app/initializers/show_user.js
    - public/javascripts/app/initializers/index_group.js
    - public/javascripts/app/initializers/index_user.js
    - public/javascripts/app/initializers/tags_question.js
    - public/javascripts/app/initializers/members.js
    - public/javascripts/app/initializers/move_group.js

    - public/javascripts/app/initializers/multiauth.js
    - public/javascripts/vendor/superfish.js

  mobile:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/app/initializers/mobile.js

  websocket:
    - public/javascripts/vendor/web-socket-js/swfobject.js
    - public/javascripts/vendor/web-socket-js/FABridge.js
    - public/javascripts/vendor/web-socket-js/web_socket.js

  show:
    - public/javascripts/vendor/jquery.autovideo.js
    - public/javascripts/app/initializers/single/question.js
    - public/javascripts/app/initializers/show_question.js
    - public/javascripts/app/initializers/panel_forms.js

stylesheets:
  base:
    - public/stylesheets/compiled/application.css
    - public/stylesheets/ui-lightness/jquery-ui.css

  mobile:
    - public/stylesheets/compiled/mobile.css

