---
javascripts:
- base:
  - jquery
  - jquery-ui
  - highlight/prettify
  - showdown
  - jquery.textarea
  - jquery.notifyBar
  - application
  - jquery.autovideo
  - jquery.autocomplete
  - openid/js/jquery.openid.min
  - components/search
  - modules/sessions
  - modules/index_question
  - modules/show_question
  - modules/new_question
  - modules/index_welcome
  - modules/members
  - modules/move_group

stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - prettify
  - ../javascripts/openid/css/style

