---
javascripts:
- base:
  - jquery
  - jquery.tools.min
  - jquery-ui
  - jquery.textarea
  - jHtmlArea
  - jquery.notifyBar
  - showdown
  - highlight/prettify
  - components/search
  - jqueryui.ricodigoComplete
  - application
  - modules/index_question
  - modules/retag
  - modules/new_question
  - modules/index_welcome
  - modules/show_user
  - modules/index_group
  - modules/index_user
  - modules/tags_question
  - modules/members
  - modules/move_group
  - modules/editor
  - multiauth

- show:
  - jquery.autovideo
  - modules/single/question
  - modules/show_question

stylesheets:
- base:
  - jquery-ui
  - compiled/application
  - prettify
  - multiauth

